# Generated by Django 4.1.9 on 2023-05-11 03:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('created_by', models.UUIDField()),
                ('last_modified_by', models.UUIDField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('gt_date_added', models.DateTimeField(auto_now_add=True)),
                ('gt_last_modified', models.DateTimeField(auto_now=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50)),
                ('default_role', models.BooleanField(default=True)),
                ('all_devices', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.AlterModelTable(
            name='organizations',
            table='organizations',
        ),
        migrations.CreateModel(
            name='LoginLogout',
            fields=[
                ('login_logout_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('token', models.TextField()),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(default=None, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.useraccount')),
            ],
            options={
                'db_table': 'login-logout',
            },
        ),
    ]
